apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: {{value}}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: {{.values.username}}/{{repositry}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{Port}}
---

ingress <-> service



chart - template + values


10 template + values
