apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  selector:
    {{ .Values.deployment.labelkey }}:  {{ .Values.deployment.labelvalue }}
  ports:
  - port: {{ .Values.deployment.port }}
    targetPort: {{.Values.deployment.port}}
    nodePort: {{.Values.service.nodePort}}
